######################################################################
# Automatically generated by qmake (1.07a) Wed Oct 6 11:42:48 2004
######################################################################

TEMPLATE    = app
TARGET      = Trabajo7
INCLUDEPATH += include/qt include

QT += opengl

# Input
HEADERS += ./include/qt/*.hpp ./include/*.hpp
SOURCES += main.cpp ./lib/qt/*.cpp ./lib/*.cpp

LIBS += -lopencv_core -lopencv_imgproc -lopencv_videoio -lopencv_imgcodecs
